### ISSUE TITLE
Data is not persistent.

### ISSUE THREAD

**Issue by albertjohnsonpc** [cgwire/kitsu-docker#35]
Hi, I can't seem to find a way to save the data from my instance.
Every time I restart the container all the data is reset. Is this intended as this is not recommended for production, or am I doing something wrong

**Comment by albertjohnsonpc** [comment]
Found myself a fix for this !!!
---
This repo didn't provide `docker compose` setup, but did put a link to another repo which gives does. 
Since I am a beginner in docker and other things, I find it very confusing and difficult. So with help of `Chat GPT` I made a docker compose `yml`. Hope this helps someone else.
---
* In a folder, create a file named `docker-compose.yml`
* Paste this in the file 

```yml
services:
  cgwire:
    image: cgwire/cgwire
    container_name: kitsu
    init: true
    tty: true
    stdin_open: true
    ports:
      - 8012:80
    volumes:
      - zou-storage:/var/lib/postgresql
      - zou-storage:/opt/zou/previews

volumes:
  zou-storage:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './zou-storage'
```

* Save the file.
* Make sure you have the folder already created. (`zou-storage` in my case) Otherwise it will give an error.
* open terminal in the same location as this compose file.
* Run `docker compose up-d`.
* Done.
* All I did is, took the docker run cmd from this repo and turned it into a docker compose format using [Composerize](https://www.composerize.com/)
* Then I asked `chat-gpt` to add the necessary lines that will store the data in a desired place, in this case the relative path of this `docker-compose.yml` file.

Hope this helps someone else. 😊😊
